name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.version }}
    strategy:
      matrix:
        version: ['2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
        with: 
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle
      - name: Run Tests
        run: bundle exec rake
